spring:
  main:
    allow-circular-references: true
  profiles:
    include: druid,mybatis,dev

security:
  register:
    provider-id: nx-auth  #CAS
    client-id: "nx-admin"
    client-secret: "xxxx"
    authorization-grant-method: post
    redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
  provider:
    nx-auth:
      authorization-uri: https://cas.xxxxx.cn/cas/oauth2.0/authorize
      token-uri: https://cas.xxxxx.cn/cas/oauth2.0/accessToken
      user-info-uri: https://cas.xxxxx.cn/cas/oauth2.0/profile
      user-name-attribute: id
      userMapping:
        email: "attributes.Email"
        name: "attributes.CnName1"
        avatar: "attributes.Avatar"




