spring:
  datasource:
    druid:
      url: jdbc:mysql://47.106.126.30:13306/vue7_2_3?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
      username: eip
      password: 123456Qr!
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      #oracle.jdbc.driver.OracleDriver|com.microsoft.sqlserver.jdbc.SQLServerDriver


dubbo:
  version:
    default: 1.0.0


server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
      force-request: true
      force-response: true
      charset: utf-8
  tomcat:
    uri-encoding: UTF-8
  undertow:
    url-charset: UTF-8


management:
  server:
    port: 9080

nx:
  amqp:
    provider: redis
  cross:
    enabled: false
    allowOrigin: "http://localhost:8088"
    whiteListDomain: "localhost,127.0.0.1"
    whiteListPort: "1080,8080,80,8081,8082"


springfox:
  documentation:
    enabled: true

xxl:
  job:
    admin: #addresses: http://192.168.1.136:8096/xxl-job-admin/
    accessToken: default_token
    executor:
      appname: ${spring.application.name}
      address:
      ip:
      port: 9999
      logpath: /var/logs/${spring.application.name}/xxljob/jobhandler
      logretentiondays: 30


