spring:
  application:
    name: portal-eureka
  profiles:
    active: dev
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: EvhUZp1qPl0O6vnOkwawbc5N/2AxJUBSwOSTB9uA43IQp0WOrtGpsV3/+ywAF22CsDCJ07scLy2yaWR66BbsOQ==
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.21:3306/7.2.2_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
          druid:
            public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIobgl5Uq9fEW2V6dLXqWJKDUZGAA3CCVasj1Yxge3STiWZ1plhxBUQgNgyRYeEUrUHzYPozfm0kL/zLlHMzcnUCAwEAAQ==
  redis:
    database: 6
    host: 192.168.1.211
    port: 6379
    password:
  activemq:
    broker-url: tcp://192.168.1.211:61616
    user:
    password:

server:
  port: 8084

jms:
  enable: true

redis:
  enable: true

# 分布式事务
seata:
  enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
