#微服务名称
csp.sentinel.app.type: 1

spring:
  cloud:
    globalcors:
      cors-configurations:
        '[/**]': # 匹配所有请求
          allowedOrigins: "*" #跨域处理 允许所有的域
          allowedMethods:     # 支持的方法
            - GET
            - POST
            - PUT
            - DELETE
    gateway:
      routes:
        - id: xxx
          uri: lb://xxxService
          predicates:
            - Path=/xxx/**
        - id: baidu
          uri: lb://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1
            - SwaggerHeaderFilter
