spring:
  application:
    name: x7plus-auth
  redis:
    database: 2
    host: 47.106.126.30
    port: 16379
    password:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: dev # mysql
      url: jdbc:mysql://47.106.126.30:13306/vue7_2?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123@456Qr!.
      driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8084


management:
  server:
    port: 18084

#限制域访问 http://127.0.0.1,http://127.0.0.1:8088
cross:
  allowOrigin: http://localhost:${server.port}
  whiteListDomain: localhost,127.0.0.1,915.com
  whiteListPort: 8080,8081,8082,80,1080

nx:
  sto:
    provider: minio
    defaultBucket: nx-bucket
    accessKey:
    secretKey:
    appId: ${spring.application.name}
    regionName: beijing
    max-connections: 200
    serverUrl: