server:
  port: 8096

#微服务名称
spring:
#  main.web-application-type: reactive
#  datasource:
#    driver-class-name: org.h2.Driver
#    druid:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:file:~/gateway/gatewaydb;MODE=MYSQL;FILE_LOCK=SOCKET;
#      username: sa
#      password: sa
#      filter:
#        wall:
#          db-type: h2
#          config:
#            multi-statement-allow: true
#            lock-table-allow: false
  cloud:
#    globalcors:
#      cors-configurations:
#        '[/**]': # 匹配所有请求
#          allowedOrigins: "*" #跨域处理 允许所有的域
#          allowedMethods: # 支持的方法
#            - GET
#            - POST
#            - PUT
#            - DELETE
    gateway:
#      dynamic-routes:
#        config-type: json #json|yaml
#      loadbalancer:
#        use404: true
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true #开启小写验证：默认feign根据服GatewayCosrconfig查找都是用的全大写
#      httpclient:
#        connect-timeout: 1000
#        response-timeout: 10s        #应答超时 java.time.Duration http状态码504
#      default-filters:
#        - SwaggerHeaderFilter
#        - StripPrefix=1
      routes:
        - id: csdn
          uri: https://www.csdn.net/
          order: 1
          predicates:
            - Path=/csdn/**
          filter:
            - StripPrefix=1
        - id: xxx
          uri: lb://xxxService
          predicates:
             - Path=/xxx/**
          filters:
            - RewritePath=/*/(?<segment>.*), /$\{segment}
            - StripPrefix=1
#           - name: CircuitBreaker #使用resilience4j断路器
#             args:
#               name: gatwayDefaultCustomizer
#               fallbackUri: forward:/defaultfallback #异常跳转

springfox:
  documentation:
    enabled: true
#    swagger-ui:
#      enabled: false


#白名单
setting:
  uriWhitelist:
    - "/api/admin/auth/login"
    - "/api/admin/v2/api-docs"
    - "/api/pc/v2/api-docs"
    - "/api/open/v2/api-docs"
