spring:
  dubbo:
    server: true

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    qos-accept-foreign-ip: false
    logger: slf4j
  registry:
    protocol: ${dubbo.protocolName:dubbo}
    address: nacos://${dubbo.nacos.address:localhost}:${dubbo.nacos.port:8848}
    parameters:
      namespace: ${dubbo.nacos.namespace:nx}
    use-as-metadata-center: false
    use-as-config-center: false
    username: ${dubbo.nacos.username:nacos}
    password: ${dubbo.nacos.password:nacos}
  metadata-report:
    address: nacos://${dubbo.nacos.address:localhost}:${dubbo.nacos.port:8848}
    protocol: ${dubbo.protocolName:dubbo}
  protocol:
    name: ${dubbo.protocolName:dubbo}
    port: ${dubbo.protocolPort:20883}
    threadpool: fixed
    threads: 500
    payload: 157286400
  provider:
    token: false
    filter: providerFilter #多个,号隔开
    group: ${dubbo.nacos.group:dev}
    version: ${dubbo.naccos.version:1.0.0}
    retries: 3
    timeout: 3000
    executes: 300
  consumer:
    timeout: 3000
    check: false
    filter: consumerFilter
    group: ${dubbo.nacos.group:dev}
    version: ${dubbo.naccos.version:1.0.0}
  config-center:
    username: ${dubbo.nacos.username:nacos}
    password: ${dubbo.nacos.password:nacos}
    namespace: ${dubbo.nacos.namespace:nx}
    group: ${dubbo.nacos.group:dev}
  reference: ${dubbo.referenceUrl}