management:
  endpoints:
    web:
      exposure:
        include: '*' #gateway
  endpoint:
    nacos-discovery:
      enabled: true
    gateway:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    env:
      enabled: true
    logfile:
      enabled: true
    skywalking:
      enabled: true
  health:
    elasticsearch:
      enabled: true
    db:
      enabled: false  #actuator包下的actuate.jdbc.DataSourceHealthIndicator会在启动时进行一次jdbc配置的健康检查，对于某些系统可能会产生warning级别的报警。因此需要在配置中禁用
    defaults:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

