#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false
#    qos-accept-foreign-ip: false
#    logger: slf4j
#  registry:
#    protocol: dubbo
#    address: "N/A"
#    metadata-report:
#      address: "N/A"

spring:
  cache:
    cache-names: outLimit，notOutLimit
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=5s,refreshAfterWrite=7s
    type: caffeine #spring推荐的负载均衡器
  autoconfigure:
    exclude: #com.alibaba.cloud.sentinel.custom.SentinelAutoConfiguration,com.alibaba.cloud.sentinel.SentinelWebAutoConfiguration,com.alibaba.cloud.sentinel.SentinelWebFluxAutoConfiguration,com.alibaba.cloud.sentinel.feign.SentinelFeignAutoConfiguration
  cloud:
    loadbalancer:
      enabled: true
      ribbon.enabled: false
    sentinel:
      enabled: false
      eager: true
      transport:
        heartbeat-interval-ms: 1000
      datasource:
        flow:
          nacos:
            data-type: json
            rule-type: flow
      filter:
        enabled: false



management:
  health:
    dubbo:
      status:
        defaults: registry,memory,load #default memory,load
        extras: load,threadpool
  endpoint:
    dubbo.enabled: true
    dubbo-shutdown.enabled: true
    dubbo-configs.enabled: true
    dubbo-services.enabled: true
    dubbo-references.enabled: true
    dubbo-properties.enabled: true

#feignConfig
feign:
  hystrix.enabled : true
  httpclient.enabled : false
  okhttp.enabled : false
  client:
    config:
      default:
        connectTimeout : 50000
        readTimeout : 50000
        loggerLevel : full
  sentinel.enabled: true


#robbinConfig
ribbon:
  eureka.enabled: true
  eager-load.enabled : true




