server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      enabled: true
      force: true
      force-request: true
      force-response: true
      charset: utf-8
  tomcat:
    uri-encoding: UTF-8
  undertow:
    url-charset: UTF-8
    accessors:
      dir: /var/logs/nx
      enabled: true
      pattern: common
      prefix: access_log
      suffix: log
    max-http-post: 0
    io-threads: 2 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 30 # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 1024 # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理,每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true    # 是否分配的直接内存

spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 1024MB
  http:
    encoding: UTF-8
  freemarker:
    enabled: false
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  web:
    resources:
      add-mappings: true
      #static-locations: /static/**
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch.matching-strategy: ant_path_matcher

springfox:
  documentation:
    enabled: false

nx:
  info:
    version: 1.0.0
    base-package: com.nx
  http-client:
    connectTimeout: 2000
    readTimeout: 10000
    file-upload:
      chunk-size-limit: 1048576 #1024 * 1024
    provider: "httpClient" #okHttp3|httpClient
  id:
    workerId:  1   #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    datacenterId: 1
  cors:
    enabled: true
    allowOrigin: http://localhost:1080
    whiteListDomain: localhost,127.0.0.1,*.915zb.com
    whiteListPort: 80,1080,1080,1082
  waf:
    enabled: false
  xss:
    enabled: false