spring:
  application:
    name: x7plus-portal
  redis:
    database: @redis.dbindex@
    host: @redis.host@
    port: @redis.port@
    password: @redis.password@
  activemq:
    broker-url:  @jms.host@
    user: @jms.user@
    password: @jms.password@
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      seata: false
      datasource:
        master:
          druid:
            name: dev # mysql
            url: @datasource.url@
            username: @datasource.username@
            password: @datasource.password@%
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            #driver-class-name: oracle.jdbc.driver.OracleDriver
            #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  data:
    mongodb:
      uri: @mongo.uri@
      host: @mongo.host@
      port: @mongo.port@
      database: @mongo.database@
      username: @mongo.username@
      password: @mongo.password@


server:
  port: 8084

jms:
  enable: true

redis:
  enable: true


#限制域访问 http://127.0.0.1,http://127.0.0.1:8088
cross:
  allowOrigin: "@allowOrigin.allowOrigin@"
  whiteListDomain: "@allowOrigin.whiteListDomain@"
  whiteListPort: "@allowOrigin.whiteListPort@"