// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseMenu: typeof import('./components/layouts/BaseMenu.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    DefineEmits: typeof import('./components/study/DefineEmits.vue')['default']
    DefineExpose: typeof import('./components/study/DefineExpose.vue')['default']
    DefineProps: typeof import('./components/study/DefineProps.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./components/common/Footer.vue')['default']
    Header: typeof import('./components/common/Header.vue')['default']
    Index: typeof import('./packages/slide-verify/SlideVerify.vue')['default']
    MyFooter: typeof import('./components/common/MyFooter.vue')['default']
    MyHeader: typeof import('./components/common/MyHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sass: typeof import('./components/study/Sass.vue')['default']
    ServiceAndPricyPolicy: typeof import('./components/common/ServiceAndPricyPolicy.vue')['default']
    SildeVerifyShow: typeof import('./packages/slide-verify/SildeVerifyShow.vue')['default']
    SlotsAttrs: typeof import('./components/study/SlotsAttrs.vue')['default']
    VerifyShow: typeof import('./packages/slide-verify/VerifyShow.vue')['default']
    Vuex: typeof import('./components/study/Vuex.vue')['default']
  }
  export interface ComponentCustomProperties {
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
